runtime: python3
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /.*
  script: main.app
  login: required
- url: /.*
  script: Background.jpg
- url: /images
  static_dir: static/images


